lune-climate/openapi-typescript-codegen

- src/templates/exportService.hbs
All the changes made in the `fix-services` step in the Makefile, have
been moved here:
- Remove CancelablePromise
- Add necessary imports
- add abstract modifier to the class
- add virtual client and config parameters to the class
- remove static modifier on the methods/endpoints
- remove throws from the documentation
- modify request to utilize the config and client provided.
- modify request response to Result
> Modify services template to fit Lune use case

- src/openApi/v2/parser/getMappedType.ts
- src/openApi/v2/parser/getType.ts
- src/openApi/v3/parser/getMappedType.ts
- src/openApi/v3/parser/getType.ts
This makes it possible to utilize the `format` property to specify which
data type is to be used in the client or it should be translated
towards. Since this property is fully open ended, we are able to suit
any case we want.
The main change in this PR is starting to take into consideration this
value to discover which type the property gets translated to, before
only the actual type of the property was used (with binary being the
only `format` supported).
No custom `format` is introduced here, only the ability to easily add
them.
Both v2 and v3 parsers are modified.
> Allow custom rich data types based on format

- src/templates/luneClient.hbs
- src/utils/registerHandlebarTemplates.ts
- src/utils/writeClient.spec.ts
- src/utils/writeClient.ts
- src/utils/writeClientClass.spec.ts
- src/utils/writeClientCore.spec.ts
- src/utils/writeClientIndex.spec.ts
- src/utils/writeClientModels.spec.ts
- src/utils/writeClientSchemas.spec.ts
- src/utils/writeClientServices.spec.ts
- src/utils/writeLuneClient.ts
This fully generates a new file whenever a generation operation is
performed.
The client has the name `luneClient.ts` and it's meant to be used by
https://github.com/lune-climate/lune-ts as a starting point for the
creation of the final client. This is highly custom behaviour for
us (Lune) to make the creation of our npm package easier.
The introduced file is a replica of the current final client as
generated by `lune-ts`. This makes it easier for us to generate the
final client in the package without extra `sed | cat` operations and
makes it a lot clearer.
> Generate custom lune base client

- .github/workflows/ci.yml
To make sure things are working as expected, add the github workflow.
The original project uses circleCI, but for our case, github actions
works wonders as well and makes it unnecessary to have circleCI setup
for it.
> Add build&test process on push

- src/openApi/v2/parser/getMappedType.spec.ts
- src/openApi/v3/parser/getMappedType.spec.ts
- test/__snapshots__/index.spec.ts.snap
Since we didn't have tests enabled for the changes done to introduce
rich data types, the tests weren't correctly updated and were failing.
For this, simply adding the actual new data type format works.
The model changes we did to fit our custom needs also needed update on
the unit tests, so the files were regenerated.
> Update tests with previously introduced changes.

- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
We were not correclty closing the comment on the service itself.
Previously there was a `throws ApiError` that was rightly removed, but
the actual closing of the comment needs to remain.
This should have been caught with the changes in the templates
themselves, but there were so many changes introduced there that I
missed this one :see_no_evil:
> Fix unclosed comment on service template

- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
This is another of the custom Lune behaviours we want. This was already
previously done, but it was missing on the imports from the services
themselves. This is done to improve ESM/CommonJS compatibilities. It
also goes in line with the current state of `lune-ts` which we wanted to
fully replicate previously.
> Add .js file extension to service imports

- src/templates/luneClient.hbs
There was a missing reference to `this` since the client is part of the
class.
> Fix luneClient template

- test/__snapshots__/index.spec.ts.snap
This was forgotten on previous changes to the luneClient template.
> Reflect latest changes on test templates

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
The current model reexports assumed the export was done only with union
types. This might not be the case, so deal with all possible cases.
This is an exact copy as to how the `index` file handles these exports.
> Fix luneClient model reexports

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
We've been seeing this pattern repeatedly in our code:
const activeId = ... // Store the "current" account id here
try {
luneClient.setAccount(id)
const result = await luneClient.somethingSomething()
doSomethingWithTheResult(result)
} finally {
luneClient.setAccount(activeId)
}
which is annoying (have to keep track of account ids), repetitive
and tricky (we need the finally block to be exception-safe).
The new helper does all that for us and allows us to convert the above
to
const result = await luneClient.withAccount(id, () => luneClient.somethingSomething())
doSomethingWithTheResult(result)
> Add an account switching withAccount() helper

- src/openApi/v2/parser/getOperation.ts
- src/openApi/v3/parser/getOperation.ts
- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
The previous behaviour for the generation of methods in a service was to
use each parameter (query, path, body, cookie etc.) separately. This
meant that if we had 5 query parameters, the method would have 5
different arguments. Due to this, using methods with many of these
parameters can become cumbersome. Named parameters are not possible and
it brings issues where trying to provide a value for an optional
parameter require us to be explicit on previous optional parameters,
ending up with calls that are hard to understand and with requiring
explicit passing of the default values.
In an effort to have both better usage and allowing each method itself
to allow account overriding, this has been changed to treat queryParams
as a single object parameter. This allows for named parameters and …
> Make queryParams an object in services

- src/openApi/v2/parser/getOperation.ts
- src/openApi/v3/parser/getOperation.ts
- src/openApi/v3/parser/getOperationRequestBody.ts
- src/openApi/v3/parser/sortByRequired.ts
- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
After some debate, we have decide to rework how we present the interface
for service methods. Two main changes are present here:
- Add option to override the account to be used on the endpoint for a
single operation. This is made with a `options` object that is
optional and currently contains an `accountId` field. If we have more
to add in the future, the object structure allows us to easily do it.
- Move both queryParams and bodyParams to the same object. This makes it
a lot easier for our clients to use and doesn't leak details about the
underlying API structure. This does require the parameters to not share
any of the property names, but this is already the case and we prefer
the tradeoff.
To note that the new `data` object that holds query and body parameters
is not nullable and it is …
> Rework methods interface

- src/templates/partials/isRequiredStrict.hbs
- src/templates/partials/typeInterface.hbs
- src/utils/registerHandlebarTemplates.ts
- test/__snapshots__/index.spec.ts.snap
The initial fix to the issue was correclty passing the default value of a
in the object parsing step itself, this was not correctly being
populated due to our custom made code.
However, this still didn't fully work since the normal handling of a
parameter assumes that when a default exists, the `?` modifier is not
needed since a default is to be provided. The result becomes:
`property: type = default`.
This can occur at parameters of the method, but since we use `properties`
as a way to have a single object parameter in the method (`data`), defaults
cannot exist inside it. The property was being set as not optional since
a default existed, but since the default cannot be populated it was
erratically just being marked as required.
To make sure that a default is still populated on …
> Fix how default values interact with optional

- src/openApi/v3/parser/getEnum.ts
- src/templates/partials/exportInterface.hbs
- test/__snapshots__/index.spec.ts.snap
- test/spec/v3.json
This is a usecase we have in our OpenAPI schema. To allow it, the enum
is allowed to pass in the parsing stage, and the template deals with this
special case by naming the enum the empty string ('').
A new model was added to the tests that triggers the new code paths to
make sure generation is working.
> Allow empty string as enum entry

- package-lock.json
- package.json
This is necessary to deploy the fixes for the empty string enum.
> Bump version (patch)

- src/openApi/v3/parser/getEnum.ts
- test/__snapshots__/index.spec.ts.snap
- test/spec/v3.json
We have a hack in place where some of our enums have `null` as an enum
value. This is done to make our response validation middleware work
correctly. We need to deal with this new value accordingly. Since we
don't actually want to show it in the models, ignore any null as an enum
value. A test was added to verify the behaviour.
This fixes the current rebuild of `lune-ts` while regenerating models from
the OpenAPI schema.
Keep in mind only one line was changed in the parsing logic, but it made
indentation change so github seems to have not understood the change
very efficiently :(
> Deal with null as an enum value

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
We forgot that error responses are processed differently from success responses so we had to modify the camel-case interceptor to handle this.
Previously ApiError.errors contained something like
{"errors":[{"error_code":"token_invalid","message":"Invalid token."}]}
Now it's
{"errors":[{"errorCode":"token_invalid","message":"Invalid token."}]}
which matches the type definitions.
This change has been introduce originally in lune-ts directly[1] but then it got overwritten in [2] since the client code is actually autogenerated.
[1] https://github.com/lune-climate/lune-ts/pull/118
[2] https://github.com/lune-climate/lune-ts/pull/120
> Fix snake case keys in error responses

- package-lock.json
- package.json
We want to release new changes.
Minor version bump because we're technically breaking backwards compatibility (see [1]).
[1] https://github.com/lune-climate/openapi-typescript-codegen/pull/39
> Bump the version to 0.1.0

- src/openApi/v3/parser/getOperation.ts
- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
- test/spec/v3.json
Currently, if a oneOf model is present at the root level we try and use its properties. However, these properties are usually unnammed making it impossible to be used. Instead, we want to rely on the whole model as the parameter itself. This is currently breaking our schema generation since we've introduced a oneOf at the root.
We solve this by using the full model in the requestBody, making it use the types of each oneOf. Additionally, a small fix to how this parameter is sent to our internal clients also needed to be done. Tests were added.
> Fix oneOf type at root level

- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
We have upgraded the template for when the content-type was json, but we now have cases where the content type is multipart/form-data. This is currently making our generation fail.
The changes are due to our custom changes to improve the user interface.
> Fix service template on multipart/form-data

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
error is of type any[1] which hides that fact that the response property can be undefined, in which case camelCaseResponse fails with something like (a stacktrace from a project using the library):
TypeError: Cannot read properties of undefined (reading 'data')
at camelCaseResponse (file:///lune/lune-shipping-csv-tool/node_modules/@lune-climate/lune/esm/client.js:35:42)
at file:///lune/lune-shipping-csv-tool/node_modules/@lune-climate/lune/esm/client.js:39:30
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async main (file:///lune/lune-shipping-csv-tool/build/index.js:145:38)
[1] I'll improve that in a separate PR
> Handle connection errors correctly in the generated client

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
error was explicitly of type "any". Similarly the "response" type was implicitly "any".
As a consequence of the former the compiler didn't notice quite a big problem in the code[1] so we've been shipping bad code.
Let's provide type annotations and make them as narrow as possible to reduce the chance of unnoticed issues left in the code.
Since we now know the type of response.data we need to silence the compiler errors on that one particular line – the comment explains why.
[1] https://github.com/lune-climate/openapi-typescript-codegen/pull/51
> Improve the type annotations in the generated client

- src/openApi/v3/parser/getOperation.ts
- test/__snapshots__/index.spec.ts.snap
Due to the latest change to fix how query parameters are handled, the `isRequired` flag on the internal model was not being correctly preserved. If the requestBody is mandatory then the whole `data` object is mandatory, same for query parameters. We were wrongly overwriting `isRequired` to whatever the query params stated, but we want to preserve this information since the requestBody has been processed at this point now.
> Fix `data` being wrongly considered optional

- package-lock.json
- package.json
We have a fairly important bugfix[1] to release.
[1] 17cf9f5cb0b6 ("Fix null enum handling inside anyOf/allOf/oneOf (#65)")
> Release version 0.1.10

- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
This enables us to augment the response with additional parameters. Eg cf-ray id or raw request/responseApiError.
> Encapsulate request result in SuccessResponse

- package-lock.json
- package.json
* Responses are now of type `SuccessResponse` which enables us to extends data within them (#67).
> Release version 0.1.11

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
https://github.com/lune-climate/openapi-typescript-codegen/pull/67 introduces SuccessResponse<T>.
This change ensures the LuneClient template populates the data accordingly.
> Update LuneClient's template to populate response with metadata

- package-lock.json
- package.json
* Add new required parameter `api-version`. It is used to populate the config parameter in LuneClient template.
> Release version 0.1.13

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
This fixes the following error: https://github.com/lune-climate/lune-ts/actions/runs/10828711568/job/30044690977?pr=670
Adding an exception because, as the comment states, mixins interfaces require the same name as the class.
> Add exception to unsafe declaration

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
If the response returns other types of content, for instance 'application/pdf' or 'image/png', applying the transformation is incorrect.
> Only apply response interceptor transformations to JSON responses

- package-lock.json
Forgotten here https://github.com/lune-climate/openapi-typescript-codegen/pull/80.
> Update package-lock.json with the newest version

- src/templates/luneClient.hbs
- test/__snapshots__/index.spec.ts.snap
In https://github.com/lune-climate/openapi-typescript-codegen/pull/79 I've disabled interceptor transformations for non-JSON responses.
I failed to update types.
I only realised when using the library: https://github.com/lune-climate/lune-ts/actions/runs/12377342754/job/34546625081?pr=770.
> Fix interceptor types

- src/client/interfaces/Operation.d.ts
- src/client/interfaces/OperationResponse.d.ts
- src/openApi/v2/parser/getOperation.ts
- src/openApi/v2/parser/getOperationResponse.ts
- src/openApi/v2/parser/getOperationResults.ts
- src/openApi/v3/parser/getOperation.ts
- src/openApi/v3/parser/getOperationExplicitAcceptHeader.ts
- src/openApi/v3/parser/getOperationImplicitAcceptHeader.ts
- src/openApi/v3/parser/getOperationResponse.ts
- src/openApi/v3/parser/getOperationResponseType.ts
- src/openApi/v3/parser/getOperationResults.ts
- src/templates/exportService.hbs
- test/__snapshots__/index.spec.ts.snap
- test/spec/v3.json
By default this library adds a `Accept: application/json` header to requests.
We want to signal that other content types are accepted also, eg 'application/pdf'.
Furthermore, Axios won't handle binary response data without the `responseType` parameter set to something other than `json` (which is the default).
Therefore, this library now set both a non-`Accept: application/json` header (if one is not explicit defined in the spec) and `responseType: arraybuffer` parameter for binary responses.
See https://axios-http.com/docs/req_config.
> Support binary responses (v3 only)
